Added a landing page
arpit456jain/Cool-Front-End-Templates pull request #568
Opened 2022-04-02 18:51 UTC by Aritra777

# Description

I have added a landing page which is mobile friendly and made with HTML, CSS, Javascript.

Fixes:  #544 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2022-04-04 11:03 UTC, VidhiBhatt01 requested changes
This looks wierd.
![image](https://user-images.githubusercontent.com/83345228/161530719-72824c86-1193-436b-bc19-8d525e4057a7.png)

It has to be responsive for all screen sizes. (navbar included). There is a typo in Navbar. It must be "Explore" instead of "Explor". Also, add this project in style_links.json

2022-04-04 11:04 UTC, VidhiBhatt01 commented
https://deploy-preview-568--cool-front-end-templates.netlify.app/landing%20page/code/

2022-04-04 17:04 UTC, Aritra777 commented
I have made the changes. Please check it out.
![Screenshot 2022-04-04 222928](https://user-images.githubusercontent.com/93366359/161595198-4277b7f2-7b68-42fb-aa5c-1d9e17fc13f3.png)

2022-04-05 11:22 UTC, VidhiBhatt01 requested changes
Fix the typo too as well as update style_links.json

2022-04-05 18:22 UTC, VidhiBhatt01 requested changes

2022-04-05 18:22 UTC, VidhiBhatt01 commented on Landing_Page/index.html
> +              Explor
Still not fixed

2022-04-06 07:20 UTC, Aritra777 commented
@VidhiBhatt01 I have fixed that.

2022-04-06 10:22 UTC, VidhiBhatt01 requested changes

2022-04-06 10:22 UTC, VidhiBhatt01 commented on Landing_Page/index.html
> +              Explor
"Explore" instead of "Explor"

2022-04-06 13:18 UTC, Aritra777 commented
@VidhiBhatt01 I have changed the word.

2022-04-07 19:16 UTC, VidhiBhatt01 approved these changes

2022-04-08 11:38 UTC, merged