Improved stationery website
arpit456jain/Cool-Front-End-Templates pull request #612
Opened 2022-04-08 08:19 UTC by Areebah03

*Fixed #541 

# Description

I have improved complete stationery website. I have added image carousel for home page, improved navbar by adding login and signup modal windows, added our products section in home page and improved footer of website. I have made about us section by adding our services and some contents and images. I have also improved contact us section.

Fixes #541

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### I have added image carousel in background and improved navbar.
| Before | After |
| ----- | ------ |
| ![ss1](https://user-images.githubusercontent.com/85051124/162391877-0e534433-b7da-49ec-bdfd-1a36295a0796.png) | ![pic1](https://user-images.githubusercontent.com/85051124/162391905-0c67de9b-b050-4088-942a-75fb31c7ebf2.png) |

![pic1 0](https://user-images.githubusercontent.com/85051124/162392084-fa38fccb-9c3c-444b-a549-cbde4e0be5a0.png)

### I have added login and signup modals.
| Login | Signup |
| ----- | ------ |
| ![pic1 1](https://user-images.githubusercontent.com/85051124/162392307-7d796589-f5d0-4b03-9fd1-c1c4bc523703.png) | ![pic1 2](https://user-images.githubusercontent.com/85051124/162392339-172db68b-e77f-47ab-8ae7-64cf9ae78b5b.png) |

### I have added our products section with images and hover effects.
| Before | After |
| ----- | ------ |
| ![ss2](https://user-images.githubusercontent.com/85051124/162392582-d465baae-b52d-4683-bc6e-25cd8949c6ee.png) | ![pic2](https://user-images.githubusercontent.com/85051124/162392622-311784b9-fc36-4015-bd16-63f98d30d858.png) |

### Improved view on map section by adding contents.
![pic2 0](https://user-images.githubusercontent.com/85051124/162392794-41243a2f-18ce-43dc-8bdb-3108b70d5019.png)

### Improved footer of the website by adding locations, contact, company with favicons.
![pic2 1](https://user-images.githubusercontent.com/85051124/162392967-839aeedb-d88a-4989-af81-d6670dc20090.png)

### Improved about us section by adding contents and images.
| Before | After |
| ----- | ------ |
| ![ss3](https://user-images.githubusercontent.com/85051124/162393346-e2efaf92-8f46-4c4c-b5c4-6b5f68001bd5.png) | ![pic3](https://user-images.githubusercontent.com/85051124/162393363-6962f3bb-787b-4005-9349-9c6750b3eb75.png) |

### Added our services section by adding images and contents.
| Before | After |
| ----- | ------ |
| ![ss4](https://user-images.githubusercontent.com/85051124/162393557-2017a229-43f4-419c-8897-6cc2467ce074.png) | ![img4](https://user-images.githubusercontent.com/85051124/162393583-59a1eea2-3c19-4cb4-bb9b-db2da81e0573.png) |

### Improved contact us section
| Before | After |
| ----- | ------ |
| ![ss5](https://user-images.githubusercontent.com/85051124/162395085-a94ecbd2-1afc-459d-8c99-e119eb93f44e.png) | ![img5](https://user-images.githubusercontent.com/85051124/162395091-a11e7999-30cb-46da-bb0f-ecc8f3c359c6.png) |

2022-04-08 15:05 UTC, VidhiBhatt01 requested changes
Good job, just make the footer responsive :)

![image](https://user-images.githubusercontent.com/83345228/162469729-c33ee8a1-5910-44ba-b7cc-60b9e59e48ab.png)

2022-04-08 15:05 UTC, VidhiBhatt01 commented
https://deploy-preview-612--cool-front-end-templates.netlify.app/stationary%20website/index.html

2022-04-08 17:27 UTC, Areebah03 commented
@VidhiBhatt01  I have made footer responsive. Kindly view.


![ss1](https://user-images.githubusercontent.com/85051124/162491903-cff9b427-1e04-410e-b50a-9b7d71e450cf.png)

2022-04-11 15:09 UTC, VidhiBhatt01 approved these changes

2022-04-12 12:47 UTC, merged