New Interface for Guardian Gym
arpit456jain/Cool-Front-End-Templates pull request #703
Opened 2022-04-28 09:22 UTC by Abh1shekSingh

# Description

I have Made New Interface Design for the Guardian Gym Project

Fixes:  #688 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

BEFORE:
![before1](https://user-images.githubusercontent.com/71981463/165721289-04d6bd91-6aca-45fa-8924-e7e93113de57.JPG)
![before2](https://user-images.githubusercontent.com/71981463/165721326-87d96cb8-c7b3-47a7-a6ea-88ff34ba8ea5.JPG)

AFTER: 
![sample1](https://user-images.githubusercontent.com/71981463/165721083-764f85a6-27bb-44e4-aa1d-14738e7fec27.JPG)
![sample2](https://user-images.githubusercontent.com/71981463/165721107-bcfd08be-9346-41e1-b879-0299da81209e.JPG)

2022-04-28 11:53 UTC, VidhiBhatt01 requested changes
Make it fully responsive

![image](https://user-images.githubusercontent.com/83345228/165746276-377b7611-5146-4c08-b6e7-caf45ea8ef55.png)

2022-04-28 11:53 UTC, VidhiBhatt01 commented
https://deploy-preview-703--cool-front-end-templates.netlify.app/gym%20website/

2022-04-28 13:26 UTC, Abh1shekSingh commented
![fixed](https://user-images.githubusercontent.com/71981463/165762650-684c00fb-606f-40f9-bec3-35a57629bda3.JPG)
FIXED @VidhiBhatt01

2022-04-29 13:13 UTC, DEEPIKA-SUK approved these changes

2022-04-29 14:45 UTC, VidhiBhatt01 approved these changes

2022-04-30 05:13 UTC, merged