Added AmazonSlider
arpit456jain/Cool-Front-End-Templates pull request #817
Opened 2022-05-14 16:26 UTC by SamarthKadam

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #786 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-05-15 05:49 UTC, VidhiBhatt01 requested changes
The navbar is getting cut. I can't accept it. You can check out videos on how to make a hamburger navbar on YouTube as well as take help from someone on the server.
![image](https://user-images.githubusercontent.com/83345228/168459076-25fcd5fd-ca6d-4467-951e-26066dc86a83.png)

2022-05-15 05:49 UTC, VidhiBhatt01 commented
https://deploy-preview-817--cool-front-end-templates.netlify.app/amazonhomepageslider/

2022-05-15 05:50 UTC, VidhiBhatt01 commented on AmazonHomePageSlider/index.html
> +    <title>Document</title>
Add a suitable title

2022-05-15 05:50 UTC, VidhiBhatt01 reviewed
Fix this too

2022-05-16 07:36 UTC, SamarthKadam commented
@VidhiBhatt01  Please review this

2022-05-16 16:31 UTC, DEEPIKA-SUK requested changes
@SamarthKadam add proper images in slider in mobile view, blurred images is not looking good.

2022-05-16 17:22 UTC, VidhiBhatt01 reviewed
I agree with deepali, rest all is awesome

2022-05-17 03:57 UTC, SamarthKadam commented
@DEEPIKA-SUK  I've mentioned before it was done considering the project built for Desktop. If you see official amazon page it is not that responsive. I can't make the images aspect ratio change.Only thing I can say is  I recommend viewers  to view on desktop mode

2022-05-17 14:16 UTC, VidhiBhatt01 approved these changes
No worries :) Thanks for contributing to our repo!

2022-05-17 14:43 UTC, SamarthKadam commented
Hoping Level 3 badge :)

2022-05-17 16:07 UTC, arpit456jain requested changes

2022-05-18 17:56 UTC, VidhiBhatt01 approved these changes

2022-05-18 18:37 UTC, merged