Local Fast Food Added
arpit456jain/Cool-Front-End-Templates pull request #849
Opened 2022-05-19 16:51 UTC by shahnehal0407

Added a new template.
This template was created for local fast food shop. It consist of food gallery and also costumer can read review and all add their review.

Fixes:  #825 

# Checklist:

- [x] I have made this from my own

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

![preview](https://user-images.githubusercontent.com/65250761/169353897-9e436d0f-0944-4ed1-b53d-e3e37ff9f430.png)

2022-05-19 16:53 UTC, shahnehal0407 commented
> Added a new template. This template was created for local fast food shop. It consist of food gallery and also costumer can read review and all add their review.
> 
> Fixes: #825
> 
> # Checklist:
> * [x]  I have made this from my own
> * [x]  My code follows the style guidelines of this project
> * [x]  I have performed a self-review of my own code
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> 
> ![preview](https://user-images.githubusercontent.com/65250761/169353897-9e436d0f-0944-4ed1-b53d-e3e37ff9f430.png)

@DEEPIKA-SUK please review it

2022-05-20 16:37 UTC, VidhiBhatt01 requested changes
1. Link issue number not previous PR number.
2. Fix these
![image](https://user-images.githubusercontent.com/83345228/169573256-73fc8859-065f-489b-b7ea-9baf0ee07d14.png)
3. Are you sure you made this on your own!?👀

2022-05-20 16:37 UTC, VidhiBhatt01 commented on Local Fast Food/index.html
> +    <title>Food Fast</title>
Fast Food and not Food Fast

2022-05-20 16:38 UTC, VidhiBhatt01 commented
https://deploy-preview-849--cool-front-end-templates.netlify.app/local%20fast%20food/

2022-05-21 04:20 UTC, DEEPIKA-SUK requested changes
@shahnehal0407 fix this
![Screenshot 2022-05-21 094903](https://user-images.githubusercontent.com/64724039/169635107-3c72bf56-addf-4e4e-a41a-865ac7d0255c.png)
.

2022-05-21 04:21 UTC, DEEPIKA-SUK requested changes
@shahnehal0407 update the title in html file.

2022-05-22 04:09 UTC, VidhiBhatt01 approved these changes

2022-05-22 17:33 UTC, merged