Added Dairy website
arpit456jain/Cool-Front-End-Templates pull request #857
Opened 2022-05-20 11:55 UTC by SamarthKadam

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #801 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

2022-05-20 17:13 UTC, VidhiBhatt01 requested changes
Make it responsive and add the project in style_links.json.
![image](https://user-images.githubusercontent.com/83345228/169578830-64c0e3eb-7e47-4dea-ae8a-f80ae47580a5.png)
![image](https://user-images.githubusercontent.com/83345228/169579020-babeb2d6-5fd2-49bb-a2fc-3663af55d323.png)

2022-05-20 17:13 UTC, VidhiBhatt01 commented on DairyProductWebsite/index.html
> +    <title>Document</title>
Add suitable title

2022-05-21 08:47 UTC, SamarthKadam commented
@VidhiBhatt01  I've made the required changes

2022-05-22 04:13 UTC, VidhiBhatt01 requested changes
Everything is perfect but this looks weird.

![image](https://user-images.githubusercontent.com/83345228/169678245-8f0b537b-4e0b-47b3-91ba-34fb3aecc2cb.png)

2022-05-22 04:35 UTC, SamarthKadam commented
@VidhiBhatt01 It looks perfect from my side. Can we please compromise this? I got a lot of issues pending as this is last week of coding period so Please

2022-05-22 04:55 UTC, VidhiBhatt01 approved these changes
Cool

2022-05-22 17:40 UTC, merged