Saas landing page
arpit456jain/Cool-Front-End-Templates pull request #880
Opened 2022-05-23 14:59 UTC by prabhkaur301

# Description
Landing page of SAAS (portfolio making service) with sign up page made with HTML, CSS (SCSS) and JavaScript.

- Responsive
- Modern UI
- Client-side form validation

Fixes:  #871 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this on my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://user-images.githubusercontent.com/57444962/169848235-c74364be-3ab4-48fc-99a6-2d49abc4a62b.mp4

2022-05-23 17:26 UTC, DEEPIKA-SUK reviewed
https://deploy-preview-880--cool-front-end-templates.netlify.app/saas%20landing%20page/

2022-05-23 17:28 UTC, DEEPIKA-SUK approved these changes

2022-05-25 17:17 UTC, prabhkaur301 commented
> @prabhkaur301 how did u make it ?? i mean from any reference or yt video or from own completely

I took reference for design from this challenge on Codewell site:-
https://www.codewell.cc/challenges/fiber-landing-page--608a7e639691700015db16d1

I created this project on my own using SCSS and Bootstrap

2022-05-26 14:26 UTC, DEEPIKA-SUK requested changes
@prabhkaur301 resolve merge conflicts.

2022-05-26 18:41 UTC, merged